### ISSUE TITLE
Video stream stops playing after 120 s

### ISSUE THREAD

**Issue by kprav33n** [kprav33n/vsmstreamer#5]
The stream starts playing well but stops after 120 s. The screen freezes with the last frame that was displayed. However, VLC seems to keep receiving packets from the server. This was observed using a Wireshark capture.

**Comment by mailrish** [comment]
I am hitting this same issue of video freezing at the 120s mark. I just started using this today and updated vlc to 3.0.5. Is there anything else needed to correct this issue?

[00007fd6acc98990] videotoolbox decoder: Using Video Toolbox to decode 'h264'
[00007fd6acc98990] videotoolbox decoder: Using Video Toolbox to decode 'h264'
[00007fd6acc98990] videotoolbox decoder: vt cvpx chroma: 420v
[00007fd6acc98990] videotoolbox decoder: Raising max DPB to 5

**real	2m3.059s**
user	0m3.492s
sys	0m3.667s


<img width="719" alt="screen shot 2018-12-11 at 4 01 42 pm" src="https://user-images.githubusercontent.com/45804865/49838147-18d27900-fd5e-11e8-8aee-c5ba671ad789.png">

**Comment by kprav33n** [comment]
This is the symptom of having multiple versions of VLC installed on your system. Please ensure that you have only the nightly version installed.
